# site settings
title: 100 Days of HomeLab
subtitle: '#100DaysOfHomeLab'
email: 100daysofhomelab@gmail.com
description: 100 Days of HomeLab is a technical challenge to help improve your IT skills.  It only has a few simple rules...
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Techno Tim

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://l.technotim.live/github
  Instagram: https://l.technotim.live/instagram
  Twitter: https://l.technotim.live/twitter
  YouTube: https://l.technotim.live/subscribe
  Twitch: https://l.technotim.live/twitch
  Discord: https://l.technotim.live/discord
  Patreon: https://l.technotim.live/patreon

google_analytics:
  id: 'G-144JZ8THDX'

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
