name: 'push-remote'

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # 3.0.2
      with:
          fetch-depth: 0

    - name: Mirror + trigger CI
      uses: timothystewart6/gitlab-mirror-and-ci-action@ea004e530874f6943f4354808361219276568fdb # 0.3+
      with:
        args: 'https://gitlab.com/${{ secrets.GITLAB_PROJECT_ID }}'
      env:
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: ${{ secrets.GITLAB_HOSTNAME }}
        GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
